insert into stations(code_2l, code_4l, code_long, ordinary_name, wikipedia_page, bart_page, airport, muni_connection, caltrain_connection, amtrak_connection, vta_light_rail_connection, end_of_line, trains_can_turn, opening_date) values
  ('RM','RICH','RICH','Richmond','https://en.wikipedia.org/wiki/Richmond_station_(California)','https://www.bart.gov/stations/rich',false,false,false,true,false,true,true,'1973-01-29'),
  ('EN','DELN','DEL N','El Cerrito del Norte','https://en.wikipedia.org/wiki/El_Cerrito_del_Norte_(BART_station)','https://www.bart.gov/stations/deln',false,false,false,false,false,false,NULL,'1973-01-29'),
  ('EP','PLZA','PLAZA','El Cerrito Plaza','https://en.wikipedia.org/wiki/El_Cerrito_Plaza_station','https://www.bart.gov/stations/plza',false,false,false,false,false,false,NULL,'1973-01-29'),
  ('NB','NBRK','N BRK','North Berkeley','https://en.wikipedia.org/wiki/North_Berkeley_station','https://www.bart.gov/stations/nbrk',false,false,false,false,false,false,false,'1973-01-29'),
  ('BK','DBRK','BRK','Downtown Berkeley','https://en.wikipedia.org/wiki/Downtown_Berkeley_station','https://www.bart.gov/stations/dbrk',false,false,false,false,false,false,false,'1973-01-29'),
  ('AS','ASHB','ASHBY','Ashby','https://en.wikipedia.org/wiki/Ashby_station_(BART)','https://www.bart.gov/stations/ashb',false,false,false,false,false,false,false,'1973-01-29'),
  ('MA','MCAR','MACAR','MacArthur','https://en.wikipedia.org/wiki/MacArthur_station_(BART)','https://www.bart.gov/stations/mcar',false,false,false,false,false,false,true,'1972-09-11'),
  ('19','19TH','19ST','19th Street Oakland','https://en.wikipedia.org/wiki/19th_Street_Oakland_station','https://www.bart.gov/stations/19th',false,false,false,false,false,false,NULL,'1972-09-11'),
  ('12','12TH','12ST','12th Street Oakland City Center','https://en.wikipedia.org/wiki/12th_Street_Oakland_City_Center_station','https://www.bart.gov/stations/12th',false,false,false,false,false,false,NULL,'1972-09-11'),
  ('OW','WOAK','W OAK','West Oakland','https://en.wikipedia.org/wiki/West_Oakland_station','https://www.bart.gov/stations/woak',false,false,false,false,false,false,false,'1974-09-16'),
  ('EM','EMBR','EMBAR','Embarcadero','https://en.wikipedia.org/wiki/Embarcadero_station','https://www.bart.gov/stations/embr',false,true,false,false,false,false,false,'1976-05-27'),
  ('MT','MONT','MONTG','Montgomery','https://en.wikipedia.org/wiki/Montgomery_Street_station','https://www.bart.gov/stations/mont',false,true,false,false,false,false,true,'1973-11-05'),
  ('PL','POWL','POWEL','Powell Street','https://en.wikipedia.org/wiki/Powell_Street_station','https://www.bart.gov/stations/powl',false,true,false,false,false,false,false,'1973-11-05'),
  ('CC','CIVC','CIVIC','Civic Center/UN Plaza','https://en.wikipedia.org/wiki/Civic_Center/UN_Plaza_station','https://www.bart.gov/stations/civc',false,true,false,false,false,false,false,'1973-11-05'),
  ('16','16TH','16ST','16th Street Mission','https://en.wikipedia.org/wiki/16th_Street_Mission_station','https://www.bart.gov/stations/16th',false,false,false,false,false,false,false,'1973-11-05'),
  ('24','24TH','24ST','24th Street Mission','https://en.wikipedia.org/wiki/24th_Street_Mission_station','https://www.bart.gov/stations/24th',false,false,false,false,false,false,true,'1973-11-05'),
  ('GP','GLEN','GLNPK','Glen Park','https://en.wikipedia.org/wiki/Glen_Park_station','https://www.bart.gov/stations/glen',false,false,false,false,false,false,false,'1973-11-05'),
  ('BP','BALB','BALPK','Balboa Park','https://en.wikipedia.org/wiki/Balboa_Park_station','http://www.bart.gov/stations/balb',false,false,false,false,false,false,false,'1973-11-05'),
  ('DC','DALY','DALY','Daly City','https://en.wikipedia.org/wiki/Daly_City_station','https://www.bart.gov/stations/daly',false,false,false,false,false,true,true,'1973-11-05'),
  ('CM','COLM','COLMA','Colma','https://en.wikipedia.org/wiki/Colma_station','https://www.bart.gov/stations/colm',false,false,false,false,false,false,false,'1996-02-24'),
  ('SS','SSAN','S SAN','South San Francisco','https://en.wikipedia.org/wiki/South_San_Francisco_station_(BART)','https://www.bart.gov/stations/ssan',false,false,false,false,false,false,false,'2003-06-22'),
  ('SB','SBRN','SBRN','San Bruno','https://en.wikipedia.org/wiki/San_Bruno_station_(BART)','https://www.bart.gov/stations/sbrn',false,false,false,false,false,false,true,'2003-06-22'),
  ('SO','SFIA','SFO','San Francisco International Airport','https://en.wikipedia.org/wiki/San_Francisco_International_Airport_station','https://www.bart.gov/stations/sfia',true,false,false,false,false,true,true,'2003-06-22'),
  ('MB','MLBR','MILL','Millbrae','https://en.wikipedia.org/wiki/Millbrae_station','https://www.bart.gov/stations/mlbr',false,false,true,false,false,true,true,'2003-06-22'),
  ('AN','ANTC','ANTOC','Antioch','https://en.wikipedia.org/wiki/Antioch_station_(BART)','http://www.bart.gov/stations/antc',false,false,false,false,false,true,true,'2018-05-26'),
  ('PC','PCTR','PITTC','Pittsburg Center','https://en.wikipedia.org/wiki/Pittsburg_Center_station','http://www.bart.gov/stations/pctr',false,false,false,false,false,false,true,'2018-05-26'),
  ('WP','PITT','BAY PT','Pittsburg/Bay Point','https://en.wikipedia.org/wiki/Pittsburg/Bay_Point_station','https://www.bart.gov/stations/pitt',false,false,false,false,false,false,true,'1996-12-07'),
  ('NC','NCON','N CNC','North Concord/Martinez','https://en.wikipedia.org/wiki/North_Concord/Martinez_station','https://www.bart.gov/stations/ncon',false,false,false,false,false,false,true,'1995-12-16'),
  ('CN','CONC','CONCD','Concord','https://en.wikipedia.org/wiki/Concord_station','https://www.bart.gov/stations/conc',false,false,false,false,false,false,true,'1973-05-21'),
  ('PH','PHIL','PHILL','Pleasant Hill/Contra Costa Centre','https://en.wikipedia.org/wiki/Pleasant_Hill/Contra_Costa_Centre_station','https://www.bart.gov/stations/phil',false,false,false,false,false,false,true,'1973-05-21'),
  ('WC','WCRK','W CRK','Walnut Creek','https://en.wikipedia.org/wiki/Walnut_Creek_station','https://www.bart.gov/stations/wcrk',false,false,false,false,false,false,true,'1973-05-21'),
  ('LF','LAFY','LAFAY','Lafayette','https://en.wikipedia.org/wiki/Lafayette_station_(BART)','https://www.bart.gov/stations/lafy',false,false,false,false,false,false,false,'1973-05-21'),
  ('OR','ORIN','ORNDA','Orinda','https://en.wikipedia.org/wiki/Orinda_station','https://www.bart.gov/stations/orin',false,false,false,false,false,false,false,'1973-05-21'),
  ('RR','ROCK','ROCKR','Rockridge','https://en.wikipedia.org/wiki/Rockridge_station','https://www.bart.gov/stations/rock',false,false,false,false,false,false,false,'1973-05-21'),
  ('LM','LAKE','LAKEM','Lake Merritt','https://en.wikipedia.org/wiki/Lake_Merritt_station','https://www.bart.gov/stations/lake',false,false,false,false,false,false,false,'1972-09-11'),
  ('FV','FTVL','FRTVL','Fruitvale','https://en.wikipedia.org/wiki/Fruitvale_station','https://www.bart.gov/stations/ftvl',false,false,false,false,false,false,true,'1972-09-11'),
  ('CL','COLS','COLIS','Coliseum','https://en.wikipedia.org/wiki/Oakland_Coliseum_station','https://www.bart.gov/stations/cols',false,false,false,false,false,false,false,'1972-09-11'),
  ('SL','SANL','SLEAN','San Leandro','https://en.wikipedia.org/wiki/San_Leandro_station','https://www.bart.gov/stations/sanl',false,false,false,false,false,false,false,'1972-09-11'),
  ('BF','BAYF','BFAIR','Bay Fair','https://en.wikipedia.org/wiki/Bay_Fair_station','https://www.bart.gov/stations/bayf',false,false,false,false,false,false,true,'1972-09-11'),
  ('HY','HAYW','HAY','Hayward','https://en.wikipedia.org/wiki/Hayward_station_(BART)','https://www.bart.gov/stations/hayw',false,false,false,false,false,false,false,'1972-09-11'),
  ('SH','SHAY','SHAY','South Hayward','https://en.wikipedia.org/wiki/South_Hayward_station','https://www.bart.gov/stations/shay',false,false,false,false,false,false,false,'1972-09-11'),
  ('UC','UCTY','UCITY','Union City','https://en.wikipedia.org/wiki/Union_City_station','https://www.bart.gov/stations/ucty',false,false,false,false,false,false,false,'1972-09-11'),
  ('FM','FRMT','FREMT','Fremont','https://en.wikipedia.org/wiki/Fremont_station_(BART)','https://www.bart.gov/stations/frmt',false,false,false,false,false,false,true,'1972-09-11'),
  ('WS','WARM','WMSPR','Warm Springs/South Fremont','https://en.wikipedia.org/wiki/Warm_Springs/South_Fremont_station','https://www.bart.gov/stations/warm',false,false,false,false,false,false,true,'2017-03-25'),
  ('OA','OAKL','OAKL','Oakland International Airport','https://en.wikipedia.org/wiki/Oakland_International_Airport_station','https://www.bart.gov/stations/oakl',true,false,false,false,false,true,true,'2014-11-22'),
  ('CV','CAST','C VLY','Castro Valley','https://en.wikipedia.org/wiki/Castro_Valley_station','https://www.bart.gov/stations/cast',false,false,false,false,false,false,false,'1997-05-10'),
  ('WD','WDUB','W DUB','West Dublin/Pleasanton','https://en.wikipedia.org/wiki/West_Dublin/Pleasanton_(BART_station)','https://www.bart.gov/stations/wdub',false,false,false,false,false,false,false,'2011-02-19'),
  ('ED','DUBL','DUBLIN','Dublin/Pleasanton','https://en.wikipedia.org/wiki/Dublin/Pleasanton_station','https://www.bart.gov/stations/dubl',false,false,false,false,false,true,true,'1997-05-10'),
  ('ML','MLPT','MILPT','Milpitas','https://en.wikipedia.org/wiki/Milpitas_station','https://www.bart.gov/stations/mlpt',false,false,false,false,false,false,false,'2020-06-13'),
  ('BE','BERY','BERRY','Berryessa/North San José','https://en.wikipedia.org/wiki/Berryessa/North_San_Jos%C3%A9_station','https://www.bart.gov/stations/bery',false,false,false,false,false,true,true,'2020-06-13');
